### ISSUE TITLE
Bug: Crash when using useNetworkActivityDevTools React Native CLI

### ISSUE THREAD

**Issue by Rokkie2412** [callstackincubator/rozenite#10]
### Describe the bug

I'm tried to implement useNetworkActivityDevTools on my app. Application build is success, but when app open, it crashed.

<img width="239" height="456" alt="Image" src="https://github.com/user-attachments/assets/fb66e19d-6a2d-4c80-8cc1-ed69e43ba5a7" />

But when I remove "useNetworkActivityDevTools" from my code, my apps can run normalnya, and on react native dev tools, tab network is available, but as it expected, it's not working because I remove useNetworkActivityDevTools from my code

React-Native: 0.77.3
"@rozenite/network-activity-plugin": "^1.0.0-alpha.5",
"@rozenite/metro": "^1.0.0-alpha.5",
"@rozenite/plugin-bridge": "^1.0.0-alpha.5",

My metro config:
```
const { getDefaultConfig, mergeConfig } = require('@react-native/metro-config');
const { wrapWithReanimatedMetroConfig } = require('react-native-reanimated/metro-config');
const { withRozenite } = require('@rozenite/metro');

const defaultConfig = getDefaultConfig(__dirname);

const customConfig = {};

const mergedConfig = mergeConfig(defaultConfig, customConfig);

const reanimatedConfig = wrapWithReanimatedMetroConfig(mergedConfig);

module.exports = withRozenite(reanimatedConfig);
```

### System Info

```shell
System:
  OS: macOS 15.5
  CPU: (8) arm64 Apple M2
  Memory: 131.06 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.17.1
    path: ~/.nvm/versions/node/v22.17.1/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v22.17.1/bin/yarn
  npm:
    version: 10.9.2
    path: ~/.nvm/versions/node/v22.17.1/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.16.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.2
      - iOS 18.2
      - macOS 15.2
      - tvOS 18.2
      - visionOS 2.2
      - watchOS 11.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2025.1 AI-251.25410.109.2511.13752376
  Xcode:
    version: 16.2/16C5032a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.14
    path: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.1
    wanted: 15.0.1
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.77.3
    wanted: 0.77.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Rozenite Version

1.0.0-alpha.5

### Reproduction

-

### Steps to reproduce

Steps to Reproduce
1. Add useNetworkActivityDevTools() in your root component (e.g., App.tsx)
2. Rebuild and run the app
3. Observe crash immediately on launch

**Comment by V3RON** [comment]
I believe this particular issue was fixed today with the release of alpha.6. Could you update the Rozenite packages and try again? Hopefully, that will help.

**Comment by Rokkie2412** [comment]
I tried installing alpha version 6, but the modules were not found. Has alpha 6 been officially released and is it available for download? @V3RON 

```
Couldn't find any versions for "@rozenite/plugin-bridge" that matches "1.0.0-alpha.6"
```

**Comment by V3RON** [comment]
It was released around 2 hours ago, so it might not be in your local cache yet. What package manager are you using? If you're using Yarn v1, try running `yarn cache clean` and then `yarn install` again.

**Comment by Rokkie2412** [comment]
I’ve already tried running yarn cache clean, removed node_modules, and deleted the yarn.lock file just in case there were any lingering caches, but it still doesn’t seem to detect version 6.

Is there something I might be missing?
