### ISSUE TITLE
[RJXS] Body from Ajax is not showing

### ISSUE THREAD

**Issue by DracotMolver** [callstackincubator/rozenite#65]
### Describe the bug

I'm using Ajax api from the library Rxjs. If I use reactotron I can see the body of my requests, but not with the @rozenite/network-activity-plugin. Currently I have version 1.0.0-alpha.10. I do see the body of the request if it is made with fetch api or with axios.

This is how it is shown.
<img width="516" height="89" alt="Image" src="https://github.com/user-attachments/assets/a97bdeb3-9ecf-49a5-8b0e-a5208ec3aec4" />

### System Info

```shell
System:
  OS: macOS 15.5
  CPU: (8) arm64 Apple M1 Pro
  Memory: 117.56 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.19.2
    path: ~/.nvm/versions/node/v20.19.2/bin/node
  Yarn:
    version: 3.6.4
    path: ~/.nvm/versions/node/v20.19.2/bin/yarn
  npm:
    version: 10.8.2
    path: ~/.nvm/versions/node/v20.19.2/bin/npm
  Watchman:
    version: 2025.05.19.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.2
      - iOS 18.2
      - macOS 15.2
      - tvOS 18.2
      - visionOS 2.2
      - watchOS 11.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.3 AI-243.25659.59.2432.13423653
  Xcode:
    version: 16.2/16C5032a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.15
    path: /usr/bin/javac
  Ruby:
    version: 2.7.8
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.1
    wanted: 15.0.1
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.9
    wanted: 0.76.9
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Rozenite Version

1.0.0

### Reproduction

No link

### Steps to reproduce

Install: "rxjs": "6.6.7"
Then make a request using ajax api: import {ajax} from 'rxjs/ajax';

link of a basic example using rxjs: https://v6.rxjs.dev/api/ajax/ajax

**Comment by V3RON** [comment]
Hey @DracotMolver 👋 
I couldn't reproduce your problem in the playground app using the canary version of Rozenite. Could you try installing it locally? It will be released to the alpha channel later today.

**Comment by NepeinAV** [comment]
I reproduced this problem and fixed here https://github.com/callstackincubator/rozenite/pull/69

**Comment by V3RON** [comment]
Hey @DracotMolver 👋 
A possible fix for your issue is included in the latest release. Please let me know if it resolves the problem.

**Comment by DracotMolver** [comment]
Hi there.
Sorry for my delayed reply. That's awesome. Gonna update and let you know. Thanks for amazing work!

**Comment by DracotMolver** [comment]
For some reason it is still happening. I can share the code due confidentiality with the company, but I am going to try to make a "replica" and share the repo with you.

**Comment by DracotMolver** [comment]
I tried to replicate the problema and I failed. It works like a charm the plugin. I wonder if the amount and type of headers might be the issue. I cannot share that part of the code because I could get fired, but I know that we sent sooo many headers and many are customs.

**Comment by V3RON** [comment]
It’s possible your request was sent before Rozenite had a chance to load. Soon, there will be a new version of the Network Activity plugin that records all traffic, including requests sent right after the app loads.
